### ISSUE TITLE
Error: Invariant failed: Cannot find droppable entry with id [#]

### ISSUE THREAD

**Issue by vbgarciag** [hello-pangea/dnd-old#4]
### Expected behavior
Being able to move an element from a sublist nested in a list to another sublist using virtualization (`react-virtuoso`)

### Actual behavior
I have a main list which each item has a sublist, when I move a draggable item from sublist to another sublist and while scrolling down I get this erro: `Error: Invariant failed: Cannot find droppable entry with id [#]`, I assume the droppable component of the source sublist is unmounted when the item of virtualized list disappears and due to that the error is shown but I'm not sure if this is a real bug, it's worth mentioning that this behavior works perfectly if I don't use a virtual list
### Steps to reproduce
Create a list and per each item create a sublist, apply virtualization to the main list and try to move an item of any sublist to another sublist (preferably to a sublist far from source sublist) the error happens when the sublist item container is unmounted by the virtualization

**Comment by Xhale1** [comment]
Perfect timing, I'm actually adding a Virtuoso example today! This is likely an issue with how you've setup Virtuoso and pangea dnd; if you have an example I could better troubleshoot.

If not, I'll let you know when that example / demo is live.

**Comment by Merynek** [comment]
Thats why.
![image](https://user-images.githubusercontent.com/6883795/185218298-0ac0177d-20f3-4794-b2d5-d97306d4488f.png)

I have same issue. I cant use dnd with virtualization when another dropable are not in DOM. Its mby better for performance, but I its limitation for me :-(

**Comment by Merynek** [comment]
Mby any flag (props) which enable adding/removing <Droppable />

**Comment by vbgarciag** [comment]
@Xhale1 Thank you, I really appreciate it! 

I recorded a short video showing the error, in this video you can see I've created 2 sandboxes with the same approach but using `@hello-pangea/dnd` and `atlassian/react-beautiful-dnd`

here are the links for the sandboxes:

1. [using @hello-pangea/dnd](https://codesandbox.io/s/floral-grass-6s62td?file=/src/row.js:106-126)
2. [using atlassian/react-beautiful-dnd](https://codesandbox.io/s/proud-wave-6gseiz?file=/src/row.js:106-128)

The goal is to be able to move rows from one sublist to another sublist by applying virtualization to the main list

**Comment by Merynek** [comment]
The problem is that you render/remove new Droppable component during drag. Its no supported in react-beautiful-dnd. Virtualization can be use only when is only one droppable content and many draggable items. Mby library @hello-pangea/dnd fix this problem in future.

**Comment by vbgarciag** [comment]
@Merynek Exactly that's the problem, hopefully, this can be allowed in the future 🤞

**Comment by Xhale1** [comment]
Please see https://github.com/hello-pangea/dnd for our new repo with improved React 18 support :)
